## 
##  Visopsys
##  Copyright (C) 1998-2006 J. Andrew McLaughlin
##  
##  Makefile
##

BUILDDIR=../../build/system/libraries

all:
	mkdir -p ${BUILDDIR}
	make -C libntfs -f Makefile.visopsys

clean:
	rm -f *~ *.o core
	make -C include/ntfs -f Makefile.visopsys clean
	make -C libntfs -f Makefile.visopsys clean
