##
##  Visopsys
##  Copyright (C) 1998-2015 J. Andrew McLaughlin
##
##  Makefile
##

BUILDDIR = ../../build/system/libraries

all:
	mkdir -p ${BUILDDIR}
	${MAKE} -C libntfs -f Makefile.visopsys DEBUG=${DEBUG}
	${MAKE} -C de
	${MAKE} -C es

clean:
	rm -f *~ *.o core
	${MAKE} -C include/ntfs -f Makefile.visopsys clean
	${MAKE} -C libntfs -f Makefile.visopsys clean
	${MAKE} -C ntfsprogs -f Makefile.visopsys clean
	${MAKE} -C de clean
	${MAKE} -C es clean

